name: CI/CD with SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set_up_JDK 17
        uses: actions/setup-java@v1
        with:
           java-version: 17  # Use the appropriate Java version

      - name: Build with Maven
        run: mvn clean install

      - name: Run SonarCloud Analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# Add any additional steps for deployment or notifications as needed
# name: cicd
# on:
#   push:
#     branches:
#       - master
 
# jobs:
#   sonarcloud:
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
    
#      

#       - name: Build with maven
#         run: mvn clean package
         
      
#       - name: Cache Maven packages
#         uses: actions/cache@v1
#         with:
#           path: ~/.m2
#           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#           restore-keys: ${{ runner.os }}-m2
#       - name: Sonarcloud Scan
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      #      SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
     
#      #   run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

#       # - name: check out code
#       #   uses: actions/checkout@v2
        
#       # - name: Configure AWS credentials
#       #   uses: aws-actions/configure-aws-credentials@v1
#       #   with:
#       #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       #        aws-region: ap-south-1

#       # - name: Login to Amazon ECR
#       #   id: login-ecr
#       #   uses: aws-actions/amazon-ecr-login@v1

#       # - name: Build, tag, and push image to Amazon ECR
#       #   id: build-image
#       #   env:
#       #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#       #         ECR_REPOSITIORY: demo3
#       #         IMAGE_TAG: ${{ github.sha }}
#       #       #run: |
#       #     # Build a docker container and
#       #     # push it to ECR so that it can
#       #     # be deployed to ECS.
#       #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#       #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#       #    # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
#       #   #  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

        
        
